// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Quran {
    license:      string;
    source:       string;
    audioEdition: string;
    data:         Datum[];
}

export interface Datum {
    number:         number;
    sequence:       number;
    numberOfVerses: number;
    name:           Name;
    revelation:     Revelation;
    tafsir:         DatumTafsir;
    preBismillah:   PreBismillah | null;
    verses:         Verse[];
}

export interface Name {
    short:           string;
    long:            string;
    transliteration: Translation;
    translation:     Translation;
}

export interface Translation {
    en: string;
    id: string;
}

export interface PreBismillah {
    text:        Text;
    translation: Translation;
    audio:       Audio;
}

export interface Audio {
    primary:   string;
    secondary: string[];
}

export interface Text {
    arab:            string;
    transliteration: Transliteration;
}

export interface Transliteration {
    en: string;
}

export interface Revelation {
    arab: Arab;
    en:   En;
    id:   IDEnum;
}

export enum Arab {
    مدينة = "مدينة",
    مكة = "مكة",
}

export enum En {
    Meccan = "Meccan",
    Medinan = "Medinan",
}

export enum IDEnum {
    Madaniyyah = "Madaniyyah",
    Makkiyyah = "Makkiyyah",
}

export interface DatumTafsir {
    id: string;
}

export interface Verse {
    number:      Number;
    meta:        Meta;
    text:        Text;
    translation: Translation;
    audio:       Audio;
    tafsir:      VerseTafsir;
}

export interface Meta {
    juz:         number;
    page:        number;
    manzil:      number;
    ruku:        number;
    hizbQuarter: number;
    sajda:       Sajda;
}

export interface Sajda {
    recommended: boolean;
    obligatory:  boolean;
}

export interface Number {
    inQuran: number;
    inSurah: number;
}

export interface VerseTafsir {
    id: IDClass;
}

export interface IDClass {
    short: string;
    long:  string;
}
